### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by kurzum** [dbpedia/dev.dbpedia.org#11]
Hi,
I am still finding it difficult to create a good structure, so here are the things that have to be updated:
1. the page inclusion should be more unified. For me there is no difference in including pages from this repo or from another repo. the problem is that readme-list.tsv only includes external pages, but why? Can't we keep all pages there?
2. If we keep all pages in readme-list.tsv it would be nice to use the order of the csv for the order of the sidebar. So you just have one place to configure everything.

**Comment by Vehnem** [comment]
1. `about.md` is the only file that has to stay in the content folder, because its the root document and i didnt want to make the bash script to complex.
New: if you want to provide static markdown, please use the `markdown` folder now.
2. I adapted the scripts/jekyll and the sidebar order is now based on the entry order of the `readme-list.tsv`
